using BiasAnalyzer.Core.Enums;
using BiasAnalyzer.Core.Models;

namespace BiasAnalyzer.Data.Seed;

public static class GaucherSeedData
{
    public static List<GaucherWord> GetWords() => new List<GaucherWord>
    {
        //Masculine words
        new() { Word = "active", BiasType = GenderBiasType.Masculine },
        new() { Word = "adventurous", BiasType = GenderBiasType.Masculine },
        new() { Word = "aggressive", BiasType = GenderBiasType.Masculine },
        new() { Word = "ambitious", BiasType = GenderBiasType.Masculine },
        new() { Word = "analytical", BiasType = GenderBiasType.Masculine },
        new() { Word = "assertive", BiasType = GenderBiasType.Masculine },
        new() { Word = "autonomous", BiasType = GenderBiasType.Masculine },
        new() { Word = "challenging", BiasType = GenderBiasType.Masculine },
        new() { Word = "athletic", BiasType = GenderBiasType.Masculine },
        new() { Word = "boastful", BiasType = GenderBiasType.Masculine },
        new() { Word = "competitive", BiasType = GenderBiasType.Masculine },
        new() { Word = "courageous", BiasType = GenderBiasType.Masculine },
        new() { Word = "decide", BiasType = GenderBiasType.Masculine },
        new() { Word = "decisive", BiasType = GenderBiasType.Masculine },
        new() { Word = "dominant", BiasType = GenderBiasType.Masculine },
        new() { Word = "greedy", BiasType = GenderBiasType.Masculine },
        new() { Word = "headstrong", BiasType = GenderBiasType.Masculine },         
        new() { Word = "hostile", BiasType = GenderBiasType.Masculine },
        new() { Word = "impulsive", BiasType = GenderBiasType.Masculine },
        new() { Word = "independent", BiasType = GenderBiasType.Masculine },
        new() { Word = "individual", BiasType = GenderBiasType.Masculine },
        new() { Word = "intellectual", BiasType = GenderBiasType.Masculine },
        new() { Word = "leader", BiasType = GenderBiasType.Masculine },
        new() { Word = "logic", BiasType = GenderBiasType.Masculine },
        new() { Word = "masculine", BiasType = GenderBiasType.Masculine },
        new() { Word = "objective", BiasType = GenderBiasType.Masculine },
        new() { Word = "opinion", BiasType = GenderBiasType.Masculine },
        new() { Word = "outspoken", BiasType = GenderBiasType.Masculine },
        new() { Word = "persist", BiasType = GenderBiasType.Masculine },
        new() { Word = "reckless", BiasType = GenderBiasType.Masculine },
        new() { Word = "stubborn", BiasType = GenderBiasType.Masculine },
        new() { Word = "superior", BiasType = GenderBiasType.Masculine },
        new() { Word = "self-confident", BiasType = GenderBiasType.Masculine },
        new() { Word = "self-sufficient", BiasType = GenderBiasType.Masculine },
        new() { Word = "self-reliant", BiasType = GenderBiasType.Masculine },
        new() { Word = "tactical", BiasType = GenderBiasType.Masculine },
        new() { Word = "genius", BiasType = GenderBiasType.Masculine },
        new() { Word = "command", BiasType = GenderBiasType.Masculine },
        new() { Word = "guru", BiasType = GenderBiasType.Masculine },
        new() { Word = "cocky", BiasType = GenderBiasType.Masculine },
        new() { Word = "burly", BiasType = GenderBiasType.Masculine },
        new() { Word = "zeal", BiasType = GenderBiasType.Masculine },
        new() { Word = "firmly", BiasType = GenderBiasType.Masculine },
        new() { Word = "journeyman", BiasType = GenderBiasType.Masculine },

        //Feminine Words
        new() { Word = "affectionate" , BiasType = GenderBiasType.Feminine},
        new() { Word = "cheerful" , BiasType = GenderBiasType.Feminine},
        new() { Word = "committed" , BiasType = GenderBiasType.Feminine},
        new() { Word = "communal" , BiasType = GenderBiasType.Feminine},
        new() { Word = "compassionate" , BiasType = GenderBiasType.Feminine},
        new() { Word = "considerate" , BiasType = GenderBiasType.Feminine},
        new() { Word = "dependable" , BiasType = GenderBiasType.Feminine},
        new() { Word = "emotional" , BiasType = GenderBiasType.Feminine},
        new() { Word = "feminine" , BiasType = GenderBiasType.Feminine},
        new() { Word = "gentle" , BiasType = GenderBiasType.Feminine},
        new() { Word = "honest" , BiasType = GenderBiasType.Feminine},
        new() { Word = "interpersonal" , BiasType = GenderBiasType.Feminine},
        new() { Word = "kind" , BiasType = GenderBiasType.Feminine},
        new() { Word = "kinship" , BiasType = GenderBiasType.Feminine},
        new() { Word = "modesty" , BiasType = GenderBiasType.Feminine},
        new() { Word = "nurturing" , BiasType = GenderBiasType.Feminine},
        new() { Word = "pleasant" , BiasType = GenderBiasType.Feminine},
        new() { Word = "polite" , BiasType = GenderBiasType.Feminine},
        new() { Word = "quiet" , BiasType = GenderBiasType.Feminine},
        new() { Word = "responsive" , BiasType = GenderBiasType.Feminine},
        new() { Word = "sensitive" , BiasType = GenderBiasType.Feminine},
        new() { Word = "submissive" , BiasType = GenderBiasType.Feminine},
        new() { Word = "supportive" , BiasType = GenderBiasType.Feminine},
        new() { Word = "together" , BiasType = GenderBiasType.Feminine},
        new() { Word = "busy" , BiasType = GenderBiasType.Feminine},
        new() { Word = "sympathetic" , BiasType = GenderBiasType.Feminine},
        new() { Word = "understanding" , BiasType = GenderBiasType.Feminine},
        new() { Word = "warm" , BiasType = GenderBiasType.Feminine},
        new() { Word = "caring" , BiasType = GenderBiasType.Feminine},
        new() { Word = "connected" , BiasType = GenderBiasType.Feminine},
 };
}